---
title: "PISA GO and KEGG"
author: "Marcin Sajek"
date: "April 28, 2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading required libraries, echo=FALSE, warning=FALSE,message=FALSE}
library(dplyr)
library(tidyverse)
library(magrittr)
library(data.table)
library(clusterProfiler)
library(org.Hs.eg.db)
library(here)
```

## reading PISA data and filtering significant ones

```{r reading_data, warning=FALSE,message=FALSE}
goi <- fread(here('data', 'PISA', 'VolPlot_PerseusExport.txt')) %>%
  filter(Significant == '+') %>%
  dplyr::select(c('Accession')) %>%
  deframe()
```

## go enrichment

```{r go, warning=FALSE,message=FALSE}
enrPISA <- enrichGO(gene = goi,
                    OrgDb = org.Hs.eg.db,
                    keyType = 'UNIPROT',
                    ont = 'ALL',
                    pvalueCutoff = 0.05,
                    pAdjustMethod = 'fdr',
                    minGSSize = 5,
                    maxGSSize = 800,
                    readable = T)

BP <- as_tibble(enrPISA) %>%
  filter(ONTOLOGY == 'BP')
#fwrite(BP, here('data','PISA_GO_BP.tsv'), sep = '\t')

MF <- as_tibble(enrPISA) %>%
  filter(ONTOLOGY == 'MF' & Count >= 5)
#fwrite(MF, here('data','PISA_GO_MF.tsv'), sep = '\t')

MF <- MF %>%
  arrange(desc(p.adjust)) %>%               # sort your dataframe
  mutate(Description = factor(Description, unique(Description))) # reset your factor-column based on that order

MFlolli <- ggplot(MF[7:21,], aes(x=Description, y=-log10(p.adjust))) +
  geom_segment( aes(x=Description, xend=Description, yend=p.adjust), color="black") +
  geom_point( color="red", size=4) +
  theme_light() + coord_flip() +
  theme(
    panel.grid.major.x = element_blank(),
    panel.border = element_blank(),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)
  ) +
  xlab("") +
  ylab("Adjusted -log10(p-Value)")

ggsave(plot = MFlolli, filename = here("plots", "Fig3_MF_goEnrich.pdf"), width = 7, height = 3)

write_csv(x = MF, col_names = TRUE, here("output", "SupTable5_GOanalysis_MFall.csv"))

CC <- as_tibble(enrPISA) %>%
  filter(ONTOLOGY == 'CC')
#fwrite(CC, here('data','PISA_GO_CC.tsv'), sep = '\t')
```

## KEGG enrichment

```{r kegg, warning=FALSE,message=FALSE}
ids <- bitr(goi, fromType = 'UNIPROT', toType = c('ENTREZID','ENSEMBL'), OrgDb = org.Hs.eg.db) 

kegg_goi <- ids %>%
  dplyr::select(c('ENTREZID')) %>%
  distinct() %>%
  na.omit() %>%
  deframe()

enrPISA_kegg <- enrichKEGG(gene = kegg_goi,
           organism = 'hsa',
           pvalueCutoff = 0.05,
           pAdjustMethod = 'fdr',
           minGSSize = 3,
          maxGSSize = 800)

kegg_res <- as_tibble(enrPISA_kegg)

kegg_res <- kegg_res %>%
  arrange(desc(p.adjust)) %>%               # sort your dataframe
  mutate(Description = factor(Description, unique(Description))) # reset your factor-column based on that order

KGlolli <- ggplot(kegg_res, aes(x=Description, y=-log10(p.adjust))) +
  geom_segment( aes(x=Description, xend=Description, yend=p.adjust), color="black") +
  geom_point( color="red", size=4) +
  theme_light() + coord_flip() +
  theme(
    panel.grid.major.x = element_blank(),
    panel.border = element_blank(),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)
  ) +
  xlab("") +
  ylab("Adjusted -log10(p-Value)")

ggsave(plot = KGlolli, filename = here("plots", "Fig3Supp_KG_goEnrich.pdf"), width = 7, height = 4)

#fwrite(kegg_res, here('data','PISA_KEGG_enrich.tsv'), sep = '\t')
```